@startuml

entity Patient
class FirstName
class LastName
class FullName
class DateOfBirth
class Gender
class MedicalRecordNumber
class ContactInformation
class AllergiesMedicalConditions
class EmergencyContact
class PatientInfoLog
class ProfileHistory

entity User
class Role
class Email

entity Staff
class StaffFirstName
class StaffLastName
class StaffFullName
class LicenseNumber
class StaffContactInformation
class AvailabilitySlots
class Specialization

entity OperationRequest
class OperationRequestID
class DeadlineDate
class Priority

entity OperationType
class OperationName
class EstimatedDuration
class Active

entity SurgeryRoom
class RoomNumber
class RoomType
class Capacity
class AssignedEquipment
class CurrentStatus

entity Appointment
class AppointmentID
class DateAndTime
class AppointmentStatus


Patient -down- FirstName
Patient -down- LastName
Patient -down- FullName
Patient -down- DateOfBirth
Patient -down- Gender
Patient -down- MedicalRecordNumber
Patient -down- ContactInformation
Patient -down- AllergiesMedicalConditions
Patient -down- EmergencyContact
PatientInfoLog -down- ProfileHistory


User -- Role
User -- Email


Staff -up- StaffFirstName
Staff -up- StaffLastName
Staff -up- StaffFullName
Staff -up- LicenseNumber
Staff -up- StaffContactInformation
Staff -up- AvailabilitySlots
Staff -up- Specialization


OperationRequest -- OperationRequestID
OperationRequest -- DeadlineDate
OperationRequest -- Priority


OperationType -- OperationName
OperationType -- EstimatedDuration
OperationType -- Active


SurgeryRoom -- RoomNumber
SurgeryRoom -- RoomType
SurgeryRoom -- Capacity
SurgeryRoom -- AssignedEquipment
SurgeryRoom -- CurrentStatus


Appointment -- AppointmentID
Appointment -- DateAndTime
Appointment -- AppointmentStatus


OperationRequest -left- OperationType
Patient -- Appointment
Patient -- PatientInfoLog
User -- Patient
User -up- Staff
Staff -- Appointment 
Staff -- OperationRequest
OperationRequest -right- Patient
Appointment -- SurgeryRoom


@enduml
