@startuml

title C4 Model - System Context Level 1
package "Surgical Appointment System"{
Rectangle "Surgical Appointment System" as System
}

Rectangle "HTTPS API: ASP.NET Core" as API

System -(0- API : Uses


@enduml